name: Build Binaries

on:
  push:
    paths-ignore:
      - '.github/*'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '*.md'

jobs:
  build:
    runs-on: windows-latest
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: microsoft/setup-msbuild@v2
    - name: Clear local NuGet cache (workaround for failed restores on windows-latest)
      run: dotnet nuget locals all --clear
    - name: Build
      run: msbuild BuildAllTargets.proj
    - name: Upload MSIX Bundle
      uses: actions/upload-artifact@v4
      with:
        name: NanaZip_Mainline.msixbundle
        path: Output/Binaries/AppPackages/**/NanaZipPackage_*_x64_arm64.msixbundle
    - name: Upload Extension Package Installer
      uses: actions/upload-artifact@v4
      with:
        name: NanaZip_Mainline_ExtensionPackage.exe
        path: Output/NanaZip.ExtensionPackage_*.exe
    - name: Upload Debug Symbols
      uses: actions/upload-artifact@v4
      with:
        name: NanaZip_Mainline_DebugSymbols.zip
        path: Output/*_DebugSymbols.zip
    - name: Upload MSBuild Build Process Binary Log
      uses: actions/upload-artifact@v4
      with:
        name: NanaZip_Mainline_BuildAllTargets.binlog
        path: Output/BuildAllTargets.binlog
